### PR TITLE
Functions to calculate mean bottom and surface values

### PR DESCRIPTION
**Pull request by sean-rohan-NOAA**
New functions:
- get_haul_events: Added to utils.R. Retrieves haul events from RACEDATA to allow calculation of mean bottom temperature and salinity.
- calc_bottom_mean: Calculate mean bottom temperature and salinity, extract sensor metadata from cnvs
- calc_surface_mean: Calculate mean surface temperature and salinity from downcasts
- remove_bad_station_data: Excludes bad ctd casts and moves cnv files from bad casts to bad_cnv

Updated:
- create_NMEA_files: Added BT gear_temperature, BT surface_temperature, BT gear_depth, and haul performance code to output to facilitate QA/QC. Updated documentation.

### CODE REVIEW

**Comment by coleary-noaa** [comment]
Currently getting package install issues: 

Error in parse(outFile) : 
  C:/Users/.../AppData/Local/Temp/RtmpS85VsZ/R.INSTALL3ca050577cb5/gapctd/R/df_to_netcdf.R:71:11: unexpected '>'
70:   # Assign index value to each cast
71:   x <- x |>
              ^
ERROR: unable to collate and parse R files for package 'gapctd'

**Comment by sean-rohan-NOAA** [comment]
@coleary-noaa Are you using R >= 4.1? This seems like an error due to the functions using R's new native pipe operators (|>).

**Comment by coleary-noaa** [comment]
All works. R update to most recent version is necessary.

`> dim(final_output)
[1] 283  31`

checked BT & salinity CTD histogram plots for quick test as well. also look good.

only issue was the usual when I connect to VPN, I need to first open the G drive folder before R can detect it.

**Comment by sean-rohan-NOAA** [comment]
Excellent, thank you!

**Pull request merged**
